apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grafana-monitoring

resources:
- ../../base/grafana/instance
- ../../base/grafana/dashboards
# - ../../base/grafana/dashboards-openshift

patches:
- target:
    kind: GrafanaDataSource
    name: thanos
  # oc sa get-token grafana-thanos
  patch: |-
    - op: replace
      path: /spec/datasources/0/secureJsonData/httpHeaderValue1
      value: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6InBhMk5uWGR0V05lazY3enNSak1QRGpnTm9JVExjR3ptcVhfY2VsS0p2Q2cifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJncmFmYW5hLW1vbml0b3JpbmciLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoiZ3JhZmFuYS10aGFub3MtdG9rZW4iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiZ3JhZmFuYS10aGFub3MiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiJiMzQzMjliNy1iMmIwLTRmZTMtYTM2Yi0yZDI3OWJhNGMzMzMiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6Z3JhZmFuYS1tb25pdG9yaW5nOmdyYWZhbmEtdGhhbm9zIn0.G23STo5iAYWEzrwN45FZXjhimh_-I5JtIW7SInCcEFI0jXegoGyki1cqCzNb_xNeZ-NQ11royfbZcNADEr44B3-nCQIUnDJfadgwGkdP_QIJ_KIcI3ajhV8nx9tp8vw0xUFBh_sn1aVj3F5SpHl2lV6fkwuVGoP2Sps5qRa74YzWnrGww0EyxXml8GasmXtjKJhTUq5n8f7np8xI0Ile0GO5zLSOh4p-hI1z8GqKmJV4D9913L2BUJQxUlZS4kKTe901JOrBsGJcHoUrWxSOAbXJCk0ZbjDx32GCXd3fGOPBMAgxilRFSXu2HIbvkLgGZvvG1wjwzSE4qnIpqVl4Jm4yeujvXgq7psYUJKLGwCRFckjk4Vjm__1s-kyEzIC8tniFOEYhfnWDo4ujpBSNpKXAuE1I1j_3ZPBk2YgaNkzB_5MunarA1pRYwgrxLK8kGHRwMji9jpypCHk9oPEyir0i-rkmOY56LwKUQPg8S83wyPuPpnlEMByhB--hGvNYqAZXVkVw2fmPhbsg8uES84_4mFuFMtKRc1pcioHBqIfKp26Qe_3n8pg7BXOCroFzmVmxITHqx-ksKC_lQQZNXFS-4PpnjEOL5D4TN_rFwz_cRU0I9AhfhPtYha3QgmYYsGvBfnCHuag9ix-sN_B-AvjBJZ0H2HZPBPHYxrqqS-0
- target:
    kind: Grafana
    name: grafana
  patch: |-
    - op: add
      path: /spec/containers/0/args/-
      value: '-openshift-sar={"resource": "namespaces", "verb": "get"}'

