apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: team-a

resources:
- ../../base/amq/instance
- ../../base/sso/instance
- ../../base/grafana/instance
- ../../base/grafana/dashboards
- ../../base/kafka/instance

patches:
- target:
    kind: GrafanaDataSource
    name: thanos
  # oc sa get-token grafana-serviceaccount
  patch: |-
    - op: replace
      path: /spec/datasources/0/url
      value: https://thanos-querier.openshift-monitoring.svc.cluster.local:9092
    - op: add
      path: /spec/datasources/0/jsonData/customQueryParameters
      value: namespace=team-a
    - op: replace
      path: /spec/datasources/0/secureJsonData/httpHeaderValue1
      value: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6InBhMk5uWGR0V05lazY3enNSak1QRGpnTm9JVExjR3ptcVhfY2VsS0p2Q2cifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJ0ZWFtLWEiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoiZ3JhZmFuYS10aGFub3MtdG9rZW4iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiZ3JhZmFuYS10aGFub3MiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiI3Y2YwMWEyNC03OTAxLTQ1MzgtODFhMS00ZmU1NGY5NWY3Y2QiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6dGVhbS1hOmdyYWZhbmEtdGhhbm9zIn0.GKg3LUzbCnZW--_FRT2JpfZv_7w5kHp6UU65TLOBg3JpcxCuiCX73dKH4Gfl1fmfAJnYbMIpVE8RY8mmdkH0R8iWvM9TuPJQRKyf9I305HaTBZJLXulaCS8n5AxDUbC2ireZ66fEomBaUmbPbyGEHzNijkO4Oej-JhO-6c9iRCIwTbQShkBGPkqLVRn-sykGPYQV-bmnNgGIJLjdWB3slmZlGdy-Gfv86L0RdUj2bee4BjtdCskhtd3Htj1dB3U4H-SzUJZvAtxCn19xS_UYh0RhtOVRTRutXt5F3edyzRDvLF6xm4UgMNfzv3570kaYKWpmJeZZh_auLDEHCZzvtDU1eCB4Nb3gGVfwmZsZxWqR8LbanLfdi3sXvVx0t_BowzI3bIbEgXbO5HY1KaVwsieWHrROssvQHL0VIjMQAMcGi_UJwa3gAAk3DkOp-Y_7Kb2LyeGiWJDBvYnRqLPSWAEP38NkmVgny4GU9Ejp-ZpHRKa0zNC4xPLiROQ2zD1H-9b04BTEIoHmTfPS7QFCmiC7WTpWSS7C5uBDF4c1BTcD9idOBSMTa14FqgI6wHuiBmFHKi41wdHM6K0R_Tx5QafUpFxuisSLdYKugAbWjSAzCZgCXSHKU-wPlfrfhAy8TPtlkHDlPYzEDZ_WQJDYc6uOtaiuTZaW2rfE_kN-dM4
- target:
    kind: Grafana
    name: grafana
  patch: |-
    - op: add
      path: /spec/containers/0/args/-
      value: '-openshift-sar={"resource": "services", "verb": "get", "namespace":"team-a"}'
- target:
    kind: PodMonitor
    name: kafka-resources-metrics
  patch: |-
    - op: replace
      path: /spec/namespaceSelector/matchNames/1
      value: team-a
    - op: replace
      path: /metadata/labels/podmonitor
      value: team-a      
