apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: team-b

resources:
- ../../base/amq/instance
- ../../base/sso/instance
- ../../base/grafana/instance
- ../../base/grafana/dashboards

patches:
- target:
    kind: GrafanaDataSource
    name: thanos
  # oc sa get-token grafana-serviceaccount
  patch: |-
    - op: replace
      path: /spec/datasources/0/url
      value: https://thanos-querier.openshift-monitoring.svc.cluster.local:9092
    - op: add
      path: /spec/datasources/0/jsonData/customQueryParameters
      value: namespace=team-b
    - op: replace
      path: /spec/datasources/0/secureJsonData/httpHeaderValue1
      value: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6InBhMk5uWGR0V05lazY3enNSak1QRGpnTm9JVExjR3ptcVhfY2VsS0p2Q2cifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJ0ZWFtLWIiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoiZ3JhZmFuYS10aGFub3MtdG9rZW4iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiZ3JhZmFuYS10aGFub3MiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiI4Y2IyODI2Ni05YmEyLTRlNDItOGZmOS03NGE4NjQxMGI2OGMiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6dGVhbS1iOmdyYWZhbmEtdGhhbm9zIn0.Ms7OiTPz-uM95_9Jcz-Mhmi2CaBvnxBaeFvIC6KnNi_FCpDnegfFxbr8O308ddUPZu2i3mu4Qhb0Y8SvYTwtEcmelu7zKEtkK1AQ479bThYmbHwgYA0H6fwUDV1Dc2bvpYu-y_-patmfA7sZKZ_zYC_UHYVYvBLfsQvZlAXjGpyRQzyWr-J_a4egMJi6ewoLv_c6vGoMIQK_8P8aqYsrfTZfiO9gh1GLZvVgOG6Mp2RlPZ6f_kafO84HWEFvKAx5_OGq1rfzvq1bIML0GK9yEeQQU5AMUUGy7OFJLlXfUjxTY3mkGV-4yJ0tZBRMoy3UZhx6GoRu7QabmAvFJ5VfJLOh6W7pGERRsJEREMhRF1eZwcV11nBZ9iPVhUb7ptaGj-UtHRbAZ4DtBdGxRNWX5Fddy6Q198wA5FtFJdVqFsVz-lxOhmRqDdrZW8kKmsxTWGK1Dt4UoR5jPw8o3-Q6XDPl1lpZpNWsWVXsQLPcXc8gy4t9yJ7ZXFJONkPzX_3XtpzGD90w65_km2cRUH15Svthe4WtB5mvAaZUe2eJvHHQcjlwm-E0jlvR9bOZpNigYUR8HI89WkkhkPcC8sxu7oVU1wvapakNcuqcvk1bOnCXRS7brZeaeZ1AfWCSg33bJiQFNYota0Sz1RJENtP4gKl9MOCa8NXmixnj1PZQDnM
- target:
    kind: Grafana
    name: grafana
  patch: |-
    - op: add
      path: /spec/containers/0/args/-
      value: '-openshift-sar={"resource": "services", "verb": "get", "namespace":"team-b"}'